import { Inter } from "next/font/google";
import { ReduxProvider } from "@/components/Providers/ReduxProvider";
import type { Metadata } from "next";
import "./globals.css";
import { HomeHeader, SearchHero } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-7xl mx-auto">
          <HomeHeader />
         {/*  <SearchHero /> */}
          <ReduxProvider>{children}</ReduxProvider>
        </div>
      </body>
    </html>
  );
}
